### ISSUE TITLE
error when running 'create_unit' function in R3.6.1

### ISSUE THREAD

**Issue by muyixu** [TongZhou2017/itol.toolkit#22]
**Describe the bug**
I get an error when I run the 'create_unit' code when I want to define the color of the tree.

**To Reproduce**
`library(itol.toolkit)`

`tree <- system.file("extdata",
                    "tree_of_itol_templates.tree",
                    package = "itol.toolkit")`

`data("template_groups")`

`df_group <- data.frame(id = unique(template_groups$group), 
                       data = unique(template_groups$group))`

`hub <- create_hub(tree = tree)`

`unit <- create_unit(data = df_group, 
                    key = "Quickstart", 
                    type = "DATASET_COLORSTRIP", 
                    tree = tree)`
It turned out like this:
![7f2beb152d8b3f8e8d9ffcba3d10cb0](https://user-images.githubusercontent.com/38967248/219996981-581f25ee-44eb-4496-8db7-c2f88b3d573d.png)

**Comment by TongZhou2017** [comment]
Depending on the huge version difference between R3.6.1 and R4 among packages, some functions do not work well in R3.6.1.

Update R to v4 and reinstalling packages will solve.

Or, adding the color parameter will also solve this error:
```R
unit <- create_unit(data = df_group,  
  key = "Quickstart",  
  type = "DATASET_COLORSTRIP", 
  color = "table2itol",
  tree = tree)
```
The function `get_color(set="ls")` will show the color name choices supported in the color parameter.

**Comment by Christina1993** [comment]
I added the ‘color’ parameter and it worked, thank you!
`
unit <- create_unit(data = df_group,  
  key = "Quickstart",  
  type = "DATASET_COLORSTRIP", 
  color = "table2itol",
  tree = tree)
`

**Comment by TongZhou2017** [comment]
Fixed in itol.toolkit v1.1.2

Please check more detail in this video:
https://www.bilibili.com/video/BV1oV4y197hB/
