### ISSUE TITLE
error when I save hubs

### ISSUE THREAD

**Issue by muyixu** [TongZhou2017/itol.toolkit#23]
I got an error when I run the function 'write_hub' function in R3.6.1. 
![image](https://user-images.githubusercontent.com/38967248/219997861-7281499b-6b92-491b-b051-17efe7523c7d.png)
However, the files are exported normally in the folder. However, in this case, the "DATASET_HEATMAP" annotation file did not work properly when imported into the iTOL. And the error information was as follows:
![image](https://user-images.githubusercontent.com/38967248/219998763-d3e239ca-92f8-4757-a11e-cee33ceb6de7.png)

**Comment by TongZhou2017** [comment]
Could you share an example file of DATASET_HEATMAP without data part？

**Comment by Christina1993** [comment]
[E8_usage_count_among_publications.txt](https://github.com/TongZhou2017/itol.toolkit/files/10779110/E8_usage_count_among_publications.txt)

**Comment by TongZhou2017** [comment]
I tested the file and get the same error information.

I opened the file by TextEdit in macOS and copied the content. And I use Vim to write a new txt file by parsing the copied strings.

The new file worked.

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/33484722/220001258-016be217-30f1-4a61-a24d-11dd78440473.png">

I think the reason is the dependent function(might be `write.table`) in R3.6.1 is different from R4.
[issue_23.txt](https://github.com/TongZhou2017/itol.toolkit/files/10779170/issue_23.txt)

**Comment by TongZhou2017** [comment]
Is `write_unit` also not work for DATASET_HEATMAP?

**Comment by Christina1993** [comment]
When I used the function 'write_unit' to export the DATASET_HEATMAP alone, the output file is a temporary file in a non-plain text format. I got an error when I upload the file into iTOL.
![image](https://user-images.githubusercontent.com/38967248/220087414-243c3583-c1f2-422b-88c1-2f0c96ea681c.png)
The function I used is `write_unit(unit_8,tempfile())`.
And here is the output file.
![image](https://user-images.githubusercontent.com/38967248/220087924-a1c31a9b-9a35-400e-b617-03ddf06ee336.png)
![image](https://user-images.githubusercontent.com/38967248/220087972-c1499cb9-f412-4ad5-9c49-cb6e4f18c746.png)

**Comment by TongZhou2017** [comment]
> When I used the function 'write_unit' to export the DATASET_HEATMAP alone, the output file is a temporary file in a non-plain text format. I got an error when I upload the file into iTOL. ![image](https://user-images.githubusercontent.com/38967248/220087414-243c3583-c1f2-422b-88c1-2f0c96ea681c.png) The function I used is `write_unit(unit_8,tempfile())`. And here is the output file. ![image](https://user-images.githubusercontent.com/38967248/220087924-a1c31a9b-9a35-400e-b617-03ddf06ee336.png) ![image](https://user-images.githubusercontent.com/38967248/220087972-c1499cb9-f412-4ad5-9c49-cb6e4f18c746.png)

How about change the file name ending with .txt? and try again?

I found the CR and LF are specific in the Windows environment.
https://knowledge.digicert.com/solution/vmc-convert-cr-lf-to-lf-before-submitting-svg.html#:~:text=In%20Notepad%2B%2B%20go%20to,the%20CR%20LF%20characters%20visually.

Try to cover them in Unix format might work.

**Comment by TongZhou2017** [comment]
Please help me to check if write_hub works in itol.toolkit v1.1.2 under R 3.6.1?
