### ISSUE TITLE
Improve the create_unit help documentation

### ISSUE THREAD

**Issue by Hua-CM** [TongZhou2017/itol.toolkit#24]
when I use the `create_unit()` function, the description for the key argument confuse me. What does "a character specifying the theme name and prefix of data name as key information for the following reproducible workflow." mean? It seems that this value only used as a file name. I hope the author could simplify this description.

**Comment by TongZhou2017** [comment]
Thanks for your suggestion.

I will simplify the `key` parameter description in v1.1.1

**Comment by TongZhou2017** [comment]
I simplified the description in v1.1.1
#25
