### ISSUE TITLE
How to get the tree for bins

### ISSUE THREAD

**Issue by diego00012138** [TongZhou2017/itol.toolkit#36]
Dear Sir
Results from iCAMP dont provide the tree for bins, How to recluster from the original tree file to get the bin tree file.
Sincerely

**Comment by TongZhou2017** [comment]
Hi

Thanks for using itol.toolkit. The method mentioned in the [paper](https://www.sciencedirect.com/science/article/abs/pii/S0269749122014579) is choosing the most abundant OTU/ASV in the bin to build a tree.

Best,
Tong
