### ISSUE TITLE
Trying to annotate using colorstrips: Error in COLOURS[[n]] : subscript out of bounds

### ISSUE THREAD

**Issue by Shyamili09** [TongZhou2017/itol.toolkit#43]
I am trying to annotate my tree using colorstrip. There are 47 different strains in my tree. So, I need to give 47 colors to my tree based on the strains. Below is my script. 

Stree <- system.file("extdata","core_gene_alignment_99perc.aln.raxml.bestTree",package = "itol.toolkit")

st_template<- read.table("ST_data.txt",header=TRUE,sep="\t")

ST_group <- data.frame(id = unique(st_template$ST_name), data = unique(st_template$ST_name))

hubs<- create_hub(tree=Stree)

unit_st<-create_unit(data=ST_group,key="ST_group",type="DATASET_COLORSTRIP",tree=Stree)
Using default color pattern: table2itol
Error in COLOURS[[n]] : subscript out of bounds

![Screenshot from 2024-04-01 17-48-42](https://github.com/TongZhou2017/itol.toolkit/assets/140464482/4bf1cfb8-3487-4757-b613-fd16e62aef78)

Here is how my file ST_data.txt look like, it has 47 different strains
NodeID	ST_name
GCA_000296595.1_ASM29659v1_genomic.fna.PROKKA_03072024	ST_398
GCA_000418345.1_ASM41834v1_genomic.fna.PROKKA_03072024	ST_239
GCA_000709475.1_ASM70947v1_genomic.fna.PROKKA_03072024	ST_239
GCA_000969225.1_ASM96922v1_genomic.fna.PROKKA_03072024	ST_105
GCA_001018645.2_ASM101864v2_genomic.fna.PROKKA_03072024	ST_1
GCA_001019305.2_ASM101930v2_genomic.fna.PROKKA_03072024	ST_5
GCA_001019435.2_ASM101943v2_genomic.fna.PROKKA_03072024	ST_5
GCA_001019455.2_ASM101945v2_genomic.fna.PROKKA_03072024	ST_30
GCA_001019495.2_ASM101949v2_genomic.fna.PROKKA_03072024	ST_5
GCA_001278745.1_ASM127874v1_genomic.fna.PROKKA_03072024	ST_5

**Comment by TongZhou2017** [comment]
The default color set has 40 colors, please use the biggest color set by adding the parameter:
color="wesanderson"

**Comment by Shyamili09** [comment]
Thank you
