### ISSUE TITLE
itol.toolkit--Color_Palette function

### ISSUE THREAD

**Issue by makerer5** [TongZhou2017/itol.toolkit#44]
Hello, I tried to assign a color to the tree. When I used the following code, I kept getting prompted: Error: Object 'Phylum_color' not found.
I compared the sample file 'abunt_metadata.txt' and did not find the Phylum_color option. Which step went wrong?
`phylum_color <- tribble(
  ~Phylum, Phylum_color,
  "Ascomycota", "#d45e00",
  "Basidiomycota", "#54c3ff",
  "Chytridiomycota", "#f0e449",
  "Entorrhizomycota", "#b04380", 
  "Rozellomycota", "#79d0ff",
  "Unassigned","#75b831",
  "Aphelidiomycota","#afb28e",
  "Calcarisporiellomycota","#98c8f3",
  "Mortierellomycota","#6a1b9a",
  "Glomeromycota","#fdfab0",
  "Monoblepharomycota","#fd8a8a",
  "Mucoromycota","#738385",
  "Olpidiomycota","#ffc46d",
  "Zoopagomycota","#ece8f2"
)`

**Comment by TongZhou2017** [comment]
Please show me the full code pipeline and example data files.

The Phylum_color object looks like a custom defined in the above code lines.
