### ISSUE TITLE
Problems with tree visualisation

### ISSUE THREAD

**Issue by wanxn518** [TongZhou2017/itol.toolkit#45]
Hi Dr Zhou

Thank you for developing toolkit, it is very helpful in presenting phylogenetic trees and I am a loyal user of it. I have a little problem in visualising the tree, can you give me some of your suggestions? Sincere thanks in advance!

My analysis gave me a tree with the details of the tree file as shown below (obviously all the branches of the tree have a length of 1), and I was wondering what the numbers marked in red in the tree file represent? It doesn't seem to be the node id inside the tree, because clicking on display node id in itol doesn't display him in the tree. The other example file refers to them as "internal_branch" and provides a visualisation of the tree.

I would like to know what these "internal_branch" mean? How are these numbers shown in the phylogenetic tree? As in the example visualisation tree provided? I think you are an expert in phylogenetic trees and may have an answer to this question. Thank you very, very much!
[S.zip](https://github.com/user-attachments/files/15532446/S.zip)

Best,
NanShao

![image](https://github.com/TongZhou2017/itol.toolkit/assets/97587984/ffa2a1bc-bc0a-4dcc-98da-32b1db97f5a1)
![image](https://github.com/TongZhou2017/itol.toolkit/assets/97587984/866a7125-37f8-4e09-befa-3efec723971d)

**Comment by TongZhou2017** [comment]
iTOL can't identify the node id only with numbers, I edit the tree node id to start with 'N' by the following code:

```
tree <- ape::read.tree("~/Downloads/S.ree")
tree$node.label <- paste0("N", tree$node.label)
ape::write.tree(tree,"~/Downloads/S_new.ree")
```

The new tree file can be identified well in iTOL
[S_new.ree.zip](https://github.com/user-attachments/files/15540341/S_new.ree.zip)

Thank you very much for using itol.toolkit.

**Comment by wanxn518** [comment]
Your help has solved my problem, thank you very much!
