### ISSUE TITLE
tbl_vars" has no method applicable to the "c('double', 'numeric')

### ISSUE THREAD

**Issue by makerer5** [TongZhou2017/itol.toolkit#46]
**Describe the bug**
When I followed the tutorial ‘’https://tongzhou2017.github.io/itol.toolkit-gallery/Zheng2022Fig3ALeft/’’ to draw an evolutionary tree, I encountered a function error. Error content: Error in UseMethod("tbl_vars") :
"tbl_vars" has no method applicable to the "c('double', 'numeric')" target object.

**To Reproduce**
1. Go to 'tree_1 <- ape::read.tree("otus.nwk")
              data_1 <- read.csv("data_1.csv")  '
2. Click on '# simple_bar by NS
               unit_4 <- create_unit(data = data_1 %>% select(ID, NS), 
                      key = "rep_Zheng2022ep_3al_4_simplebar", 
                      type = "DATASET_SIMPLEBAR",
                      tree = tree_1)'
3. See error: Error in UseMethod("tbl_vars") :
"tbl_vars" has no method applicable to the "c('double', 'numeric')" target object.

**Expected behavior**
I want to construct a bar plot of otu abundance by ''General'' group

**Screenshots**
![image](https://github.com/user-attachments/assets/ccec2316-4bba-4c31-8e02-3034817fb439)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Googel]
 - Version [1.1.8
[data_1.csv](https://github.com/user-attachments/files/16827285/data_1.csv)
]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TongZhou2017** [comment]
use data.table::fread to read metadata file or use as.data.table to convert data.frame to data.table format.

**Comment by makerer5** [comment]
Thank you very much, thanks to your code, this problem is solved
